global.hosts.domain: khanhtranhuy.io.vn 
global.hosts.externalIP: 10.31.200.1 
installCertmanager: false 
global.ingress.configureCertmanager: false 
global.ingress.annotations."kubernetes\.io/tls-acme": true 
gitlab.webservice.ingress.tls.secretName: personal-gitlab-tls 
registry.ingress.tls.secretName: personal-registry-tls 
minio.ingress.tls.secretName: personal-minio-tls 
gitlab.kas.ingress.tls.secretName: personal-kas-tls
gitlab-runner.runners.privileged: true