apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    path: ./
    repoURL: https://github.com/khanhtranhuy/gitlab.git
    targetRevision: main
    helm:
      releaseName: gitlab
      value: |
        global.hosts.domain: khanhtranhuy.io.vn
        global.hosts.externalIP: 10.31.200.5
        certmanager-issuer.email=khanhtranhuy9x@gmail.com
        installCertmanager: false
        global.ingress.configureCertmanager: false
        global.ingress.annotations."kubernetes\.io/tls-acme": true
        gitlab.webservice.ingress.tls.secretName: personal-gitlab-tls
        registry.ingress.tls.secretName: personal-registry-tls
        minio.ingress.tls.secretName: personal-minio-tls
        gitlab.kas.ingress.tls.secretName: personal-kas-tls
        gitlab-runner.runners.privileged: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true